import { simulator } from "./flexi-config.js";
import { SimulatorStore, canOpenStage, completeStage, finishAttempt, learnerInitials, recordEvent } from "./core.js";
import { calculateVolume, evaluateExpression, isCorrectMassCalculation, isCorrectVolumeCalculation } from "./calculations.js";
import { downloadFlexiEvidencePdf } from "./flexi-pdf.js";

const store = new SimulatorStore(simulator);
let state = store.load();
store.save(state);
const app = document.querySelector("#app");
const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" })[character]);
const persist = () => store.save(state);
function draft() { state.draft ||= { massExpression: "", massResult: null, massChecked: false, volume: { lengthM: "", widthM: "", heightM: "" }, volumeResult: null, volumeChecked: false }; return state.draft; }
function renderLearnerStart() { window.history.replaceState({}, "", window.location.pathname); app.innerHTML = `${header()}<main class="shell" id="main-content"><section class="card learner-start"><div class="card-header"><p class="eyebrow">Before you begin</p><h1>Enter your name</h1></div><form class="card-body" id="learner-form"><p>Enter your name to begin this FlexiFreight calculation activity.</p><label class="field">Full name<input name="learnerName" autocomplete="name" required autofocus><span class="help">Enter your first and last name.</span></label><p class="message error" id="message" aria-live="polite"></p><div class="actions"><button class="button button-primary">Start calculation tools</button></div></form></section></main>`; document.querySelector("#reset").addEventListener("click", resetAttempt); document.querySelector("#learner-form").addEventListener("submit", (event) => { event.preventDefault(); const name = new FormData(event.currentTarget).get("learnerName").trim(); const initials = learnerInitials(name); if (name.split(/\s+/).filter(Boolean).length < 2 || initials.length < 2) { document.querySelector("#message").textContent = "Enter your first and last name to begin."; return; } state.learner = { name, initials }; recordEvent(state, "learner_recorded", { initials }); persist(); renderStage(); }); }
function applyRoute() { const requested = window.location.hash.slice(1); if (simulator.stages.some((stage) => stage.id === requested) && canOpenStage(simulator, state, requested)) state.activeStage = requested; }
function header(completion = false) { return `<header class="site-header"><div class="brand"><div class="brand-mark" aria-hidden="true">FTS</div><div><strong>FlexiFreight Operations</strong><span>${completion ? "Job completion record" : "Digital calculation tools · TLIE0009"}</span></div></div>${completion ? "" : '<button class="button button-secondary" id="reset">Reset session</button>'}</header>`; }
function progress(stage) { return `<nav class="progress" aria-label="Simulator stages">${simulator.stages.map((item) => `<button data-stage="${item.id}" class="${state.completedStages.includes(item.id) ? "is-complete" : ""}" ${item.id === stage.id ? 'aria-current="step"' : ""} ${item.id !== stage.id && !state.completedStages.includes(item.id) ? "disabled" : ""}>${esc(item.label)}</button>`).join("")}</nav>`; }
function jobBanner() { return `<section class="job-banner" aria-label="Current FlexiFreight job"><div><span>Job reference</span><strong>FF-2560</strong></div><div><span>Load allocation</span><strong>18 pallets</strong></div><div><span>Loaded pallet mass</span><strong>995 kg</strong></div></section>`; }
function messagePanel(result, unit) { const display = result === null ? "No result calculated yet" : `${Number(result).toLocaleString("en-AU", { maximumFractionDigits: 3 })} ${unit}`; return `<section class="result-panel ${result === null ? "is-pending" : ""}" aria-live="polite"><span>Displayed result</span><strong>${display}</strong></section>`; }
function massWorkspace() { const d = draft(); const keys = ["7", "8", "9", "/", "4", "5", "6", "×", "1", "2", "3", "-", "0", ".", "⌫", "+", "C", "="].map((key) => `<button class="calculator-key ${["/", "×", "-", "+"].includes(key) ? "operator" : ""} ${key === "=" ? "equals" : ""} ${key === "C" ? "clear" : ""}" type="button" data-key="${key}">${key}</button>`).join(""); return `<article class="card"><div class="card-header"><p class="eyebrow">Tool 1 of 2</p><div class="tool-title"><span class="tool-icon" aria-hidden="true">1</span><h2>Digital calculator</h2></div><p>Use the calculator to check the load mass. You may type an expression, then press Enter, or use the calculator buttons.</p></div><div class="card-body"><div class="calculator"><input class="calculator-display" id="calculator-expression" inputmode="decimal" autocomplete="off" aria-label="Calculator expression" value="${esc(d.massExpression)}" placeholder="0"><div class="calculator-grid">${keys}</div></div>${messagePanel(d.massResult, "kg")}<label class="check-field"><input type="checkbox" id="mass-checked" ${d.massChecked ? "checked" : ""}>I checked the entered values, multiplication operation and displayed result before using it.</label><p class="message error" id="message" aria-live="polite"></p><div class="actions"><button class="button button-primary" id="mass-submit">Save verified load mass</button></div></div></article>`; }
function volumeWorkspace() { const d = draft(); const v = d.volume; return `<article class="card"><div class="card-header"><p class="eyebrow">Tool 2 of 2</p><div class="tool-title"><span class="tool-icon" aria-hidden="true">2</span><h2>FlexiFreight load calculator</h2></div><p>Enter the load dimensions, then calculate the cubic volume.</p></div><div class="card-body"><table class="system-table"><thead><tr><th scope="col">Load dimension</th><th scope="col">Value</th></tr></thead><tbody><tr><td>Length</td><td>9.6 m</td></tr><tr><td>Width</td><td>2.4 m</td></tr><tr><td>Height</td><td>1.2 m</td></tr></tbody></table><form id="volume-form"><div class="dimension-grid"><label class="field">Length (m)<input name="lengthM" inputmode="decimal" value="${esc(v.lengthM)}" required></label><label class="field">Width (m)<input name="widthM" inputmode="decimal" value="${esc(v.widthM)}" required></label><label class="field">Height (m)<input name="heightM" inputmode="decimal" value="${esc(v.heightM)}" required></label></div><div class="actions"><button class="button button-secondary" type="button" id="volume-calculate">Calculate volume</button></div>${messagePanel(d.volumeResult, "m³")}<label class="check-field"><input type="checkbox" id="volume-checked" ${d.volumeChecked ? "checked" : ""}>I checked the entered dimensions, units and displayed result before using it.</label><p class="message error" id="message" aria-live="polite"></p><div class="actions"><button class="button button-primary">Save verified load volume</button></div></form></div></article>`; }
function renderStage() { applyRoute(); const stage = simulator.stages.find((item) => item.id === state.activeStage); const workspace = stage.id === "mass" ? massWorkspace() : volumeWorkspace(); app.innerHTML = `${header()}<main class="shell" id="main-content"><section class="brief"><p class="eyebrow">Guided workplace simulation</p><h1>${esc(simulator.title)}</h1><p>Complete both calculation tools for FlexiFreight job FF-2560. Your progress stays only in this browser until you reset it.</p></section>${jobBanner()}${progress(stage)}<section class="grid"><article class="card"><div class="card-header"><p class="eyebrow">Current task</p><h2>${esc(stage.prompt)}</h2></div><div class="card-body"><p>${esc(stage.instruction)}</p><h3>Before you save</h3><ul class="task-list"><li>Use the supplied workplace values and the correct unit.</li><li>Check that the displayed result is reasonable.</li><li>Record the final results and completion code in 03A.</li></ul></div></article>${workspace}</section></main>`; bindShared(); if (stage.id === "mass") bindMass(); else bindVolume(); }
function bindShared() { document.querySelector("#reset").addEventListener("click", resetAttempt); document.querySelectorAll("[data-stage]").forEach((button) => button.addEventListener("click", () => { state.activeStage = button.dataset.stage; persist(); renderStage(); })); }
function showError(text) { document.querySelector("#message").textContent = text; }
function bindMass() { const d = draft(); const expression = document.querySelector("#calculator-expression"); const calculate = () => { const result = evaluateExpression(d.massExpression); d.massResult = result?.result ?? null; persist(); renderStage(); }; expression.addEventListener("input", (event) => { d.massExpression = event.target.value.replace(/[^0-9.+\-*/×xX]/g, "").replace(/[xX]/g, "×").slice(0, 16); d.massResult = null; persist(); }); expression.addEventListener("keydown", (event) => { if (event.key === "Enter") { event.preventDefault(); calculate(); } }); document.querySelectorAll("[data-key]").forEach((button) => button.addEventListener("click", () => { const key = button.dataset.key; if (key === "C") { d.massExpression = ""; d.massResult = null; } else if (key === "⌫") { d.massExpression = d.massExpression.slice(0, -1); d.massResult = null; } else if (key === "=") { return calculate(); } else if (d.massExpression.length < 16) { d.massExpression += key === "×" ? "×" : key; d.massResult = null; } persist(); renderStage(); })); document.querySelector("#mass-checked").addEventListener("change", (event) => { d.massChecked = event.target.checked; persist(); }); document.querySelector("#mass-submit").addEventListener("click", () => { if (!isCorrectMassCalculation(d.massExpression, simulator.massTask)) return showError("Use 18 × 995 and confirm the displayed result before continuing."); if (!d.massChecked) return showError("Confirm that you checked the calculation before continuing."); completeStage(simulator, state, "mass", { tool: "Digital calculator", expression: d.massExpression, result: String(d.massResult) }); persist(); renderStage(); }); }
function bindVolume() { const d = draft(); const form = document.querySelector("#volume-form"); form.querySelectorAll("input[name]").forEach((input) => input.addEventListener("input", (event) => { d.volume[event.target.name] = event.target.value; d.volumeResult = null; persist(); })); document.querySelector("#volume-calculate").addEventListener("click", () => { d.volumeResult = calculateVolume(d.volume); persist(); renderStage(); }); document.querySelector("#volume-checked").addEventListener("change", (event) => { d.volumeChecked = event.target.checked; persist(); }); form.addEventListener("submit", (event) => { event.preventDefault(); if (!isCorrectVolumeCalculation(d.volume, simulator.volumeTask) || d.volumeResult === null) return showError("Enter the supplied three dimensions and calculate the load volume before continuing."); if (!d.volumeChecked) return showError("Confirm that you checked the calculation before continuing."); completeStage(simulator, state, "volume", { tool: "FlexiFreight load calculator", ...d.volume, result: String(d.volumeResult) }); finishAttempt(simulator, state); persist(); renderCompletion(); }); }
function renderCompletion() { window.history.replaceState({}, "", "#completion"); const mass = state.fields.mass; const volume = state.fields.volume; app.innerHTML = `${header(true)}<main class="shell"><section class="card completion"><p class="eyebrow">Calculation tools complete</p><h1>FlexiFreight results verified</h1><p>Record the results and completion code in your 03A Performance Assessment, then download the evidence PDF if your assessor requires it.</p><dl class="completion-summary"><dt>Verified load mass</dt><dd>${esc(mass.result)} kg</dd><dt>Verified load volume</dt><dd>${esc(volume.result)} m³</dd><dt>Completion code</dt><dd class="completion-code">${esc(state.completion.code)}</dd></dl><p class="note privacy-note">This code and report are learner-provided evidence. They are not authenticated evidence and do not make a final competency decision.</p><div class="actions"><button class="button button-primary" id="pdf">Download evidence PDF</button><button class="button button-secondary" id="reset">Start a new session</button></div></section></main>`; document.querySelector("#pdf").addEventListener("click", () => downloadFlexiEvidencePdf({ state, config: simulator })); document.querySelector("#reset").addEventListener("click", resetAttempt); }
function resetAttempt() { if (!window.confirm("Reset this local attempt? Your saved activity and completion code will be removed from this browser.")) return; state = store.reset(); renderLearnerStart(); }
if (!state.learner?.name) renderLearnerStart(); else if (state.completion) renderCompletion(); else renderStage();
